##3. 통계수학 및 내장함수

- R에는 자체 제공하는 내장함수가 있다
- 이외에 사용자가 함수를 정의할 수도 있다 (나중에 다룰 예정)
- 내장함수 중 기본적인 몇 개만 소개하면 다음과 같다

In [ ]:
sum

function (..., na.rm = FALSE)  .Primitive("sum")

In [ ]:
game <- c(1, 2, 8, 6, 4, 4)
sum(game)

[1] 25

- median (중앙값): 위로 아래로 50%의 데이터가 있는 위치의 값

In [ ]:
max(game); min(game);
prod(game); mean(game);
median(game)

[1] 8

[1] 1

[1] 1536

[1] 4.166667

[1] 4

- 백분위수 (0.25, 0.50 0.75): 아래로 25%, 50%, 75%의 자료가 있는 위치의 값

In [ ]:
print(quantile(game))
print(quantile(game,probs=c(0.25,0.50,0.75)))

  0%  25%  50%  75% 100%
 1.0  2.5  4.0  5.5  8.0
25% 50% 75%
2.5 4.0 5.5

- 분산: 자료에서 평균을 빼고 제곱해서 (자료의 갯수-1)로 나눈 값
- round(*,4): 소수 4자리로 표기
- sort(a): 벡터 a의 값을 작은 값부터 큰 값 순으로 다시 정렬

In [ ]:
var(game); round(sd(game),4);
print(sqrt(game))
print(game(order(game)))
print(sort(game))

[1] 6.566667

[1] 2.5626

[1] 1.000000 1.414214 2.828427 2.449490 2.000000 2.000000

ERROR: Error in game(order(game)): could not find function "game"

- IQR (inter quartile range): 백분위수 75%에서 백분위수 25%를 뺀 값, 자료의 50%가 몰려 있는 중앙의 범위(길이)

In [ ]:
median(game)
IQR(game)

[1] 4

[1] 3

- 수학함수: log, exp, sin

In [ ]:
n=10; x=3
log(n, x)

[1] 2.095903

In [ ]:
exp(x)

[1] 20.08554

In [ ]:
sin(x) # cos(x), tan(x), asin(x), acos(x), atan(x)

[1] 0.14112

In [ ]:
abs(x)

[1] 3

In [ ]:
sqrt(x)

[1] 1.732051

In [ ]:
round(x, digits=2)

[1] 3

In [ ]:
factorial(x+2)

[1] 120

##**과제4**##  

$(cos \theta + sin \theta), \theta \in \{ 0, 2, 4 \}$를 계산하는 R 코드를 작성하시오.

## 4. 행렬
-- 행과 열을 가지는 2차원 구조의 배열
	$$ M = \left(m_{ij}\right), ~ i = 1, \ldots, n; j = 1, \ldots, p $$
-- 예 : $2 \times 2$ 행렬
	$$ M = \left(\begin{array}{cc} m_{11} & m_{12} \\ m_{21} & m_{22} \end{array}\right) $$
-- 예 : $3 \times 2$ 행렬
	$$ M = \left(\begin{array}{cc} m_{11} & m_{12} \\ m_{21} & m_{22} \\ m_{31} & m_{32} \end{array}\right) $$
    

- matrix(x, n, p)는 x를 원소로 가지는 n × p 행렬을 만든다. 벡터를 행이나 열로 쌓아 놓은 것으로도 볼 수 있다.

In [ ]:
M <- matrix(1:12, nrow = 4, ncol = 3)
print(M)

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

In [ ]:
M.1 <- matrix(1:12, nrow = 4, ncol = 3, byrow = TRUE)
print(M.1)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[4,]   10   11   12

In [ ]:
matrix(0,2,3)

     [,1] [,2] [,3]
[1,] 0    0    0
[2,] 0    0    0

In [ ]:
matrix(NA,1,5)

     [,1] [,2] [,3] [,4] [,5]
[1,] NA   NA   NA   NA   NA


- 1:10을 4*3 행렬에 넣기 위해서 (1,2,...,10)에 (1,2)를 추가한다.
- 여기에서 숫자를 채우는 방식은 열단위임에 유의해야 함.

In [ ]:
M.2 <- matrix(1:10, nrow = 4, ncol = 3)
print(M.2)

Warning message in matrix(1:10, nrow = 4, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [4]”

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7    1
[4,]    4    8    2

- 인덱싱(indexing): 부행렬(submatrix)을 추출한다.

In [ ]:
set.seed(1)
n <- 5
p <- 3
x <- rnorm(n*p)   # rnorm()은 정규분포로부터 난수를 생성해주는 함수
A <- matrix(x, nrow = n, ncol = p)
print(A)

           [,1]       [,2]       [,3]
[1,] -0.6264538 -0.8204684  1.5117812
[2,]  0.1836433  0.4874291  0.3898432
[3,] -0.8356286  0.7383247 -0.6212406
[4,]  1.5952808  0.5757814 -2.2146999
[5,]  0.3295078 -0.3053884  1.1249309

In [ ]:
print(A[1:3, 1:2])

           [,1]       [,2]
[1,] -0.6264538 -0.8204684
[2,]  0.1836433  0.4874291
[3,] -0.8356286  0.7383247

In [ ]:
print(A[1:3,-3]) # -는 해당 첨자를 제외한다는 의미임

           [,1]       [,2]
[1,] -0.6264538 -0.8204684
[2,]  0.1836433  0.4874291
[3,] -0.8356286  0.7383247

In [ ]:
print(A[c(1,3,5),1]) ; print(A[1,]) ; print(A[1,][1:2])

[1] -0.6264538 -0.8356286  0.3295078
[1] -0.6264538 -0.8204684  1.5117812
[1] -0.6264538 -0.8204684

- a는 벡터임.
- 차원은 길이만 있기에 NULL로 나오며, mode와 class 구문을 통해서 객체의 타입을 확인할 수 있음.

In [ ]:
A[,-2] ; a = A[,2]
dim(a) ; mode(a) ; class(a)

     [,1]       [,2]
[1,] -0.6264538  1.5117812
[2,]  0.1836433  0.3898432
[3,] -0.8356286 -0.6212406
[4,]  1.5952808 -2.2146999
[5,]  0.3295078  1.1249309

NULL

[1] "numeric"

[1] "numeric"

- 필터링 : 선별조건에 부합하는 부행렬을 추출한다.

In [ ]:
print(A[1,]>0) ; print(A[1,A[1,]>0])
print(A[,1]>0) ; print(A[A[,1]>0,1])

[1] FALSE FALSE  TRUE
[1] 1.511781
[1] FALSE  TRUE FALSE  TRUE  TRUE
[1] 0.1836433 1.5952808 0.3295078

In [ ]:
print(A[A[,1] > 0 & A[,2] > 0, ])  # and 연산자

          [,1]      [,2]       [,3]
[1,] 0.1836433 0.4874291  0.3898432
[2,] 1.5952808 0.5757814 -2.2146999

In [ ]:
print(A[A[,1] > 0 | A[,2] > 0, ]) # or 연산자

           [,1]       [,2]       [,3]
[1,]  0.1836433  0.4874291  0.3898432
[2,] -0.8356286  0.7383247 -0.6212406
[3,]  1.5952808  0.5757814 -2.2146999
[4,]  0.3295078 -0.3053884  1.1249309

##**과제5**##

$2*k \ (k=1, 2, ..., 300)$으로 $100 × 3$행렬을 만들고, 각 열별로 3으로 나누었을 때 0이 되는 값들을 추출하는 R 코드를 작성하여 그 코드와 결과를 제출하시오.

- 행렬간의 산술연산

  - 행렬 A와 B의 합(차)은 두 행렬이 같은 형태일 때 정의된다.

  - 같은 위치의 원소끼리의 합(차)로 정의된다.**bold text**
	\begin{eqnarray*}
		& A = \left(a_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}, ~ B = \left(b_{ij}\right)_{i=1,\ldots,n;j=1,\ldots,p} & \\
		& A \pm B = \left(a_{ij} \pm b_{ij}\right)_{i=1,\ldots,n;j=1,\ldots,p}&
	\end{eqnarray*}

In [ ]:
A = matrix(1:4, nrow = 2, ncol = 2)
B = matrix(5:8, nrow = 2, ncol = 2)
print(A); print(B); print(A+B)

     [,1] [,2]
[1,]    1    3
[2,]    2    4
     [,1] [,2]
[1,]    5    7
[2,]    6    8
     [,1] [,2]
[1,]    6   10
[2,]    8   12

In [ ]:
print(A+B)

     [,1] [,2]
[1,]    6   10
[2,]    8   12

In [ ]:
print(A-B)

     [,1] [,2]
[1,]   -4   -4
[2,]   -4   -4

 - 행렬 A와 B의 곱은 A의 열 수와 B의 행 수가 같을 때 정의된다
	\begin{eqnarray*}
		& A = \left(a_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}, ~ B = \left(b_{jk}\right)_{j=1,\ldots,p;k=1,\ldots,q} & \\
		& AB = \left(\sum_{j=1}^pa_{ij}b_{jk}\right)_{i=1,\ldots,n;k=1,\ldots,q}&
	\end{eqnarray*}

In [ ]:
A = matrix(1:6, nrow = 3, ncol = 2)
B = matrix(7:12, nrow = 2, ncol = 3)
print(A %*% B)

     [,1] [,2] [,3]
[1,]   39   49   59
[2,]   54   68   82
[3,]   69   87  105

- 행렬 A와 스칼라 c의 곱은 다음과 같이 정의된다.
	\begin{eqnarray*}
		& A = \left(a_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}, ~ cA =  \left(ca_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}&
	\end{eqnarray*}

In [ ]:
print(A*3)

     [,1] [,2]
[1,]    3   12
[2,]    6   15
[3,]    9   18

- 행렬 A의 전치(transpose) 행렬은 행과 열을 바꾼 행렬이다.
	\begin{eqnarray*}
		& A = \left(a_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}, ~ A^\top =  \left(a_{ji}\right)_{j=1,\ldots,p; i=1, \ldots, n}&
	\end{eqnarray*}

In [ ]:
A = matrix(6:1, nrow = 3, ncol = 2)
print(A)
print(t(A))

     [,1] [,2]
[1,]    6    3
[2,]    5    2
[3,]    4    1
     [,1] [,2] [,3]
[1,]    6    5    4
[2,]    3    2    1


- 정사각행렬 $C$의 역행렬 $C^{−1}$은 다음과 같이 정의된다.
$$C^{-1}C=CC^{-1}=I_n,~I_n\mbox{ : 항등행렬}$$

In [ ]:
C = matrix(c(16, 4, 1, 4, 4, 1, 1, 1, 1), 3, 3)
print(C)
print(solve(C))

     [,1] [,2] [,3]
[1,]   16    4    1
[2,]    4    4    1
[3,]    1    1    1
            [,1]        [,2]       [,3]
[1,]  0.08333333 -0.08333333  0.0000000
[2,] -0.08333333  0.41666667 -0.3333333
[3,]  0.00000000 -0.33333333  1.3333333

In [ ]:
print(solve(C)%*%C)

              [,1] [,2] [,3]
[1,]  1.000000e+00    0    0
[2,] -5.551115e-17    1    0
[3,]  0.000000e+00    0    1

  - 행렬의 곱에 %*%이 아니라 * 기호를 쓰면 각 요소별 연산이 수행된다.
     - 두 행렬의 크기가 같을 때 정의된다.
	\begin{eqnarray*}
		& A = \left(a_{ij}\right)_{i=1,\ldots,n; j=1, \ldots, p}, ~ B = \left(b_{ij}\right)_{i=1,\ldots,n;j=1,\ldots,p} & \\
		& A * B = \left(a_{ij}b_{ij}\right), ~ A / B = \left(a_{ij} / b_{ij}\right)&
	\end{eqnarray*}

In [ ]:
A = matrix(6:1, nrow = 3, ncol = 2)
B = matrix(1:6, nrow = 3, ncol = 2)
print(A*B)
print(A/B)

     [,1] [,2]
[1,]    6   12
[2,]   10   10
[3,]   12    6
         [,1]      [,2]
[1,] 6.000000 0.7500000
[2,] 2.500000 0.4000000
[3,] 1.333333 0.1666667

##**과제6**##

선형연립방정식
-- 행렬을 이용하여 다음 선형연립방정식의 해를 구하여라.
\begin{eqnarray*}
		2x + 3y &=& 5 \\
		3x + 4y &=& 4 \\
		\left(\begin{array}{cc} 2 & 3 \\ 3 & 4\end{array}\right)\left(\begin{array}{c}x \\ y\end{array}\right) &=& \left(\begin{array}{cc}5 \\ 4\end{array}\right)
\end{eqnarray*}
아래 관계를 이용하여 문제를 푸시오.
\begin{eqnarray*}
		A x = b
		\rightarrow
		x = A^{-1}b
\end{eqnarray*}

In [5]:
# 행렬 A 정의
A <- matrix(c(2, 3, 3, 4), nrow = 2, ncol = 2)
# 벡터 b 정의
b <- matrix(c(5, 4), nrow = 2, ncol = 1)
# 선형 연립방정식의 해 구하기
x <- solve(A, b)
# 결과 출력
x
print(x)

     [,1]
[1,] -8
[2,]  7

     [,1]
[1,]   -8
[2,]    7

- 행렬의 결합

  - 벡터 혹은 행렬을 결합하여 더 큰 행렬을 만들 수 있다

  - 예: cbind()는 같은 길이의 벡터 혹은 같은 행의 개수를 가지는 행렬을 열에 넣어 묶어주는 R 함수

In [ ]:
year=2001:2006 ; game=c(1,2,8,6,4,4); era=c(5,4,3,4,5,6)
print(cbind(year, game, era))

     year game era
[1,] 2001    1   5
[2,] 2002    2   4
[3,] 2003    8   3
[4,] 2004    6   4
[5,] 2005    4   5
[6,] 2006    4   6

- 클래스에서는 행렬, 모드에서는 수치형, 차원에서는 2*3이 반환됨

In [ ]:
stat = matrix(1:6, 2,3);
print(class(stat)); print(mode(stat)) ; print(dim(stat))

[1] "matrix" "array"
[1] "numeric"
[1] 2 3

In [ ]:
nrow(stat) ; ncol(stat)

[1] 2

[1] 3

In [ ]:
print(cbind(A,B))
print(rbind(A,B))

     [,1] [,2] [,3] [,4]
[1,]    6    3    1    4
[2,]    5    2    2    5
[3,]    4    1    3    6
     [,1] [,2]
[1,]    6    3
[2,]    5    2
[3,]    4    1
[4,]    1    4
[5,]    2    5
[6,]    3    6

예: rbind()는 같은 길이의 벡터 혹은 같은 열의 개수를 가지는 행렬을 열에 넣어 묶어주는 R 함수

In [ ]:
e <- c("Park", "LA Dodgers")
f <- c("Choo", "Texas Rangers")
g <- c("Kang", "Pittsburgh Pirates")
M <- rbind(e, f, g)
print(M)

  [,1]   [,2]
e "Park" "LA Dodgers"
f "Choo" "Texas Rangers"
g "Kang" "Pittsburgh Pirates"

- 행과 열에 함수 적용하기

  - apply()는 행렬의 각 행이나 각 열에 연산을 적용할 수 있다.
  - 사용법:
     - apply(matrix, 1, f): 행렬의 행에 함수 f를 적용
     - apply(matrix, 2, f): 행렬의 열에 함수 f를 적용

In [ ]:
M <- matrix(sample(1:6), 3, 2)
print(M)

     [,1] [,2]
[1,]    2    3
[2,]    1    5
[3,]    4    6

In [ ]:
print(apply(M, 1, sum)) ; print(apply(M, 2, sum))

[1]  5  6 10
[1]  7 14

In [ ]:
rowSums(M); colSums(M)

[1]  5  6 10

[1]  7 14

In [ ]:
print(apply(M, 1, prod)); print(apply(M, 2, prod))

[1]  6  5 24
[1]  8 90

- 척도화 scaling [평균-표준편차 표준화]

$$ z_{ij} = \frac{x_{ij} - m_j}{s_j}, ~ i = 1, \ldots, n; ~ j = 1, \ldots, p, $$

여기서 $m_j$는 열 $j$의 평균이고, $s_j$는 열 $j$의 표준편차이다.

*이탤릭체 텍스트*

In [7]:
n <- 100
set.seed(111)
X <- matrix(rnorm(n*4), n, 4)
print(dim(X))
m <- apply(X, 2, mean) ; print(m)
s <- apply(X, 2, sd) ; print(s)

[1] 100   4
[1] -0.01281906 -0.01686710  0.13638304  0.02312441
[1] 1.0708550 1.0191621 0.9168738 0.9583472

In [8]:
X.1 <- t(apply(X, 1, "-", m)) # 행의 각 원소에 대해서 다른 평균으로 뺌
X.2 <- t(apply(X.1, 1, "/", s)) # goddml 각 원소에 대해서 다른 표준편차들로 나눔
# print(X.2)
m <- apply(X.2, 2, mean) ; print(m)
s <- apply(X.2, 2, sd) ; print(s)

[1] -1.162265e-18  1.911448e-18 -3.191756e-18  1.689404e-17
[1] 1 1 1 1

In [9]:
print(head(round(X.2, 2), 3))  # 둘째 자리에서 반올림하고 앞의 세개의 행만 출력
a = round( apply(X.2, 2, scale), 2) # 열 단위로 표준편차가 1이 되게 하는 변환
print(apply(a,2,sd))

      [,1]  [,2]  [,3]  [,4]
[1,]  0.23  0.60 -0.47  0.13
[2,] -0.30 -1.12 -0.80  0.36
[3,] -0.28  0.45  0.75 -0.23
[1] 1.0001722 0.9999278 1.0003100 0.9999323

In [11]:
ss = head(round(t((t(X) - m)/s - m ),2),3) # 열단위로 벡터화되기 때문에 전치행렬을 이용해서 표준화를 하고 다시 전치행렬을 이용해서 변환
print(ss)

      [,1]  [,2]  [,3]  [,4]
[1,]  0.24  0.60 -0.30  0.14
[2,] -0.33 -1.16 -0.59  0.36
[3,] -0.31  0.44  0.83 -0.20

##**과제7**##

행렬의 각 열에 대하여, 최소값 0과 최대값 1이 되도록 하는 R 코드를
작성하시오.
$$z_{ij} = \frac{x_{ij} - m_j}{M_j - m_j}, ~ i = 1, \ldots, n; ~ j = 1, \ldots, p,$$
여기서 $m_j$는 열 $j$의 최소값이고, $M_j$는 열 $j$의 최대값이다.

In [27]:
# 샘플 데이터 생성
set.seed(123)
n <- 100  # 행 수
p <- 4    # 열 수
X <- matrix(rnorm(n * p), n, p)

# 최소값과 최대값 계산
m <- apply(X, 2, min)  # 각 열의 최소값
M <- apply(X, 2, max)  # 각 열의 최대값

# z_ij 계산
Z <- t(apply(X, 1, function(x) (x - m) / (M - m)))

# 결과 확인
print(head(Z, 3))  # 변환된 결과의 첫 3개 행 출력

min_Z <- apply(Z, 2, min)  # 각 열의 최소값
max_Z <- apply(Z, 2, max)  # 각 열의 최대값

# 최소값과 최대값 출력
min_Z
max_Z

          [,1]      [,2]      [,3]      [,4]
[1,] 0.3889008 0.2536396 0.9767215 0.3475347
[2,] 0.4623575 0.4363441 0.7578367 0.3401009
[3,] 0.8601969 0.3412273 0.3682783 0.3032066

[1] 0 0 0 0

[1] 1 1 1 1

- 4.6 행과 열에 이름 붙이기

    - rownames()와 colnames()는 각각 행과 열에 이름을 붙여준다.

In [ ]:
n <- 10
X <- matrix(round(rnorm(n*4, 50, 10)), n, 4)
print(X)

      [,1] [,2] [,3] [,4]
 [1,]   46   35   48   52
 [2,]   36   41   52   65
 [3,]   50   61   62   43
 [4,]   46   42   58   55
 [5,]   38   48   44   61
 [6,]   50   60   46   53
 [7,]   79   51   41   50
 [8,]   47   62   39   18
 [9,]   43   34   34   50
[10,]   52   22   60   53

In [ ]:
rownames(X) <- paste("S", 1:n, sep ="") # S1, S2, S#n의 문자열을 생성 #
colnames(X) <- c("math", "engl", "science", "arts")
print(X)

    math engl science arts
S1    46   35      48   52
S2    36   41      52   65
S3    50   61      62   43
S4    46   42      58   55
S5    38   48      44   61
S6    50   60      46   53
S7    79   51      41   50
S8    47   62      39   18
S9    43   34      34   50
S10   52   22      60   53

- 행렬의 선형 인덱싱

  - 행렬의 선형인덱싱 (linear indexing)을 통해서 값에 접근할 수 있다.
	\begin{eqnarray*}
		& A : n \times p \mbox{ 행렬 }& \\
		& A[i,j] = A[(j-1) * n + i] &
	\end{eqnarray*}

In [ ]:
A <- matrix(c(2, 6, 9, 4, 2, 8, 3, 5, 1), 3, 3)
A[3,2] ; A[(3-1) * 3 + 3]  #A[3,3]

[1] 8

[1] 1

- 4.8 고차원 배열
  - R 에서는 3차원이상의 배열을 만들 수 있다.

In [ ]:
firsttest <- matrix(c(46, 41, 50, 30, 25, 50),3,2)
secondtest <- matrix(c(46, 41, 50, 43, 35, 50),3,2)
tests <- array(data=c(firsttest, secondtest), dim=c(3, 2, 2))
tests <- array(data=c(46, 41, 50, 30, 25, 50, 46, 41, 50, 43, 35, 50), dim=c(3, 2, 2))

print(class(tests))
print(tests)
print(tests[,,1]) # 마지막 첨자 고정
print(tests[1,,]) # 첫번째 첨자가 1인 경우는 ,,1에서 46,30, ,,2에서 46,43임에 유의

[1] "array"
, , 1

     [,1] [,2]
[1,]   46   30
[2,]   41   25
[3,]   50   50

, , 2

     [,1] [,2]
[1,]   46   43
[2,]   41   35
[3,]   50   50

     [,1] [,2]
[1,]   46   30
[2,]   41   25
[3,]   50   50
     [,1] [,2]
[1,]   46   46
[2,]   30   43